// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: journal.proto

package io.ewok.gds.journal.messages;

public interface HeapEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gds.wal.HeapEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.gds.wal.StorageCreate create = 1;</code>
   */
  io.ewok.gds.journal.messages.StorageCreate getCreate();
  /**
   * <code>.gds.wal.StorageCreate create = 1;</code>
   */
  io.ewok.gds.journal.messages.StorageCreateOrBuilder getCreateOrBuilder();

  public io.ewok.gds.journal.messages.HeapEntry.PayloadCase getPayloadCase();
}
