// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: journal.proto

package io.ewok.gds.journal.messages;

/**
 * Protobuf type {@code gds.wal.JournalEntry}
 */
public  final class JournalEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gds.wal.JournalEntry)
    JournalEntryOrBuilder {
  // Use JournalEntry.newBuilder() to construct.
  private JournalEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JournalEntry() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private JournalEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.ewok.gds.journal.messages.XLogEntry.Builder subBuilder = null;
            if (resourceCase_ == 1) {
              subBuilder = ((io.ewok.gds.journal.messages.XLogEntry) resource_).toBuilder();
            }
            resource_ =
                input.readMessage(io.ewok.gds.journal.messages.XLogEntry.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.XLogEntry) resource_);
              resource_ = subBuilder.buildPartial();
            }
            resourceCase_ = 1;
            break;
          }
          case 18: {
            io.ewok.gds.journal.messages.TxnAcctEntry.Builder subBuilder = null;
            if (resourceCase_ == 2) {
              subBuilder = ((io.ewok.gds.journal.messages.TxnAcctEntry) resource_).toBuilder();
            }
            resource_ =
                input.readMessage(io.ewok.gds.journal.messages.TxnAcctEntry.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.TxnAcctEntry) resource_);
              resource_ = subBuilder.buildPartial();
            }
            resourceCase_ = 2;
            break;
          }
          case 26: {
            io.ewok.gds.journal.messages.StorageEntry.Builder subBuilder = null;
            if (resourceCase_ == 3) {
              subBuilder = ((io.ewok.gds.journal.messages.StorageEntry) resource_).toBuilder();
            }
            resource_ =
                input.readMessage(io.ewok.gds.journal.messages.StorageEntry.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.StorageEntry) resource_);
              resource_ = subBuilder.buildPartial();
            }
            resourceCase_ = 3;
            break;
          }
          case 34: {
            io.ewok.gds.journal.messages.HeapEntry.Builder subBuilder = null;
            if (resourceCase_ == 4) {
              subBuilder = ((io.ewok.gds.journal.messages.HeapEntry) resource_).toBuilder();
            }
            resource_ =
                input.readMessage(io.ewok.gds.journal.messages.HeapEntry.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.HeapEntry) resource_);
              resource_ = subBuilder.buildPartial();
            }
            resourceCase_ = 4;
            break;
          }
          case 42: {
            io.ewok.gds.journal.messages.IndexEntry.Builder subBuilder = null;
            if (resourceCase_ == 5) {
              subBuilder = ((io.ewok.gds.journal.messages.IndexEntry) resource_).toBuilder();
            }
            resource_ =
                input.readMessage(io.ewok.gds.journal.messages.IndexEntry.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.IndexEntry) resource_);
              resource_ = subBuilder.buildPartial();
            }
            resourceCase_ = 5;
            break;
          }
          case 50: {
            io.ewok.gds.journal.messages.CheckpointEntry.Builder subBuilder = null;
            if (resourceCase_ == 6) {
              subBuilder = ((io.ewok.gds.journal.messages.CheckpointEntry) resource_).toBuilder();
            }
            resource_ =
                input.readMessage(io.ewok.gds.journal.messages.CheckpointEntry.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.CheckpointEntry) resource_);
              resource_ = subBuilder.buildPartial();
            }
            resourceCase_ = 6;
            break;
          }
          case 58: {
            io.ewok.gds.journal.messages.BlobEntry.Builder subBuilder = null;
            if (resourceCase_ == 7) {
              subBuilder = ((io.ewok.gds.journal.messages.BlobEntry) resource_).toBuilder();
            }
            resource_ =
                input.readMessage(io.ewok.gds.journal.messages.BlobEntry.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.BlobEntry) resource_);
              resource_ = subBuilder.buildPartial();
            }
            resourceCase_ = 7;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalEntry_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ewok.gds.journal.messages.JournalEntry.class, io.ewok.gds.journal.messages.JournalEntry.Builder.class);
  }

  private int resourceCase_ = 0;
  private java.lang.Object resource_;
  public enum ResourceCase
      implements com.google.protobuf.Internal.EnumLite {
    XLOG(1),
    TXN_ACCT(2),
    STORAGE(3),
    HEAP(4),
    INDEX(5),
    CHECKPOINT(6),
    BLOB(7),
    RESOURCE_NOT_SET(0);
    private final int value;
    private ResourceCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResourceCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResourceCase forNumber(int value) {
      switch (value) {
        case 1: return XLOG;
        case 2: return TXN_ACCT;
        case 3: return STORAGE;
        case 4: return HEAP;
        case 5: return INDEX;
        case 6: return CHECKPOINT;
        case 7: return BLOB;
        case 0: return RESOURCE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResourceCase
  getResourceCase() {
    return ResourceCase.forNumber(
        resourceCase_);
  }

  public static final int XLOG_FIELD_NUMBER = 1;
  /**
   * <code>.gds.wal.XLogEntry xlog = 1;</code>
   */
  public io.ewok.gds.journal.messages.XLogEntry getXlog() {
    if (resourceCase_ == 1) {
       return (io.ewok.gds.journal.messages.XLogEntry) resource_;
    }
    return io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.XLogEntry xlog = 1;</code>
   */
  public io.ewok.gds.journal.messages.XLogEntryOrBuilder getXlogOrBuilder() {
    if (resourceCase_ == 1) {
       return (io.ewok.gds.journal.messages.XLogEntry) resource_;
    }
    return io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance();
  }

  public static final int TXN_ACCT_FIELD_NUMBER = 2;
  /**
   * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
   */
  public io.ewok.gds.journal.messages.TxnAcctEntry getTxnAcct() {
    if (resourceCase_ == 2) {
       return (io.ewok.gds.journal.messages.TxnAcctEntry) resource_;
    }
    return io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
   */
  public io.ewok.gds.journal.messages.TxnAcctEntryOrBuilder getTxnAcctOrBuilder() {
    if (resourceCase_ == 2) {
       return (io.ewok.gds.journal.messages.TxnAcctEntry) resource_;
    }
    return io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance();
  }

  public static final int STORAGE_FIELD_NUMBER = 3;
  /**
   * <code>.gds.wal.StorageEntry storage = 3;</code>
   */
  public io.ewok.gds.journal.messages.StorageEntry getStorage() {
    if (resourceCase_ == 3) {
       return (io.ewok.gds.journal.messages.StorageEntry) resource_;
    }
    return io.ewok.gds.journal.messages.StorageEntry.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.StorageEntry storage = 3;</code>
   */
  public io.ewok.gds.journal.messages.StorageEntryOrBuilder getStorageOrBuilder() {
    if (resourceCase_ == 3) {
       return (io.ewok.gds.journal.messages.StorageEntry) resource_;
    }
    return io.ewok.gds.journal.messages.StorageEntry.getDefaultInstance();
  }

  public static final int HEAP_FIELD_NUMBER = 4;
  /**
   * <code>.gds.wal.HeapEntry heap = 4;</code>
   */
  public io.ewok.gds.journal.messages.HeapEntry getHeap() {
    if (resourceCase_ == 4) {
       return (io.ewok.gds.journal.messages.HeapEntry) resource_;
    }
    return io.ewok.gds.journal.messages.HeapEntry.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.HeapEntry heap = 4;</code>
   */
  public io.ewok.gds.journal.messages.HeapEntryOrBuilder getHeapOrBuilder() {
    if (resourceCase_ == 4) {
       return (io.ewok.gds.journal.messages.HeapEntry) resource_;
    }
    return io.ewok.gds.journal.messages.HeapEntry.getDefaultInstance();
  }

  public static final int INDEX_FIELD_NUMBER = 5;
  /**
   * <code>.gds.wal.IndexEntry index = 5;</code>
   */
  public io.ewok.gds.journal.messages.IndexEntry getIndex() {
    if (resourceCase_ == 5) {
       return (io.ewok.gds.journal.messages.IndexEntry) resource_;
    }
    return io.ewok.gds.journal.messages.IndexEntry.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.IndexEntry index = 5;</code>
   */
  public io.ewok.gds.journal.messages.IndexEntryOrBuilder getIndexOrBuilder() {
    if (resourceCase_ == 5) {
       return (io.ewok.gds.journal.messages.IndexEntry) resource_;
    }
    return io.ewok.gds.journal.messages.IndexEntry.getDefaultInstance();
  }

  public static final int CHECKPOINT_FIELD_NUMBER = 6;
  /**
   * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
   */
  public io.ewok.gds.journal.messages.CheckpointEntry getCheckpoint() {
    if (resourceCase_ == 6) {
       return (io.ewok.gds.journal.messages.CheckpointEntry) resource_;
    }
    return io.ewok.gds.journal.messages.CheckpointEntry.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
   */
  public io.ewok.gds.journal.messages.CheckpointEntryOrBuilder getCheckpointOrBuilder() {
    if (resourceCase_ == 6) {
       return (io.ewok.gds.journal.messages.CheckpointEntry) resource_;
    }
    return io.ewok.gds.journal.messages.CheckpointEntry.getDefaultInstance();
  }

  public static final int BLOB_FIELD_NUMBER = 7;
  /**
   * <code>.gds.wal.BlobEntry blob = 7;</code>
   */
  public io.ewok.gds.journal.messages.BlobEntry getBlob() {
    if (resourceCase_ == 7) {
       return (io.ewok.gds.journal.messages.BlobEntry) resource_;
    }
    return io.ewok.gds.journal.messages.BlobEntry.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.BlobEntry blob = 7;</code>
   */
  public io.ewok.gds.journal.messages.BlobEntryOrBuilder getBlobOrBuilder() {
    if (resourceCase_ == 7) {
       return (io.ewok.gds.journal.messages.BlobEntry) resource_;
    }
    return io.ewok.gds.journal.messages.BlobEntry.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resourceCase_ == 1) {
      output.writeMessage(1, (io.ewok.gds.journal.messages.XLogEntry) resource_);
    }
    if (resourceCase_ == 2) {
      output.writeMessage(2, (io.ewok.gds.journal.messages.TxnAcctEntry) resource_);
    }
    if (resourceCase_ == 3) {
      output.writeMessage(3, (io.ewok.gds.journal.messages.StorageEntry) resource_);
    }
    if (resourceCase_ == 4) {
      output.writeMessage(4, (io.ewok.gds.journal.messages.HeapEntry) resource_);
    }
    if (resourceCase_ == 5) {
      output.writeMessage(5, (io.ewok.gds.journal.messages.IndexEntry) resource_);
    }
    if (resourceCase_ == 6) {
      output.writeMessage(6, (io.ewok.gds.journal.messages.CheckpointEntry) resource_);
    }
    if (resourceCase_ == 7) {
      output.writeMessage(7, (io.ewok.gds.journal.messages.BlobEntry) resource_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resourceCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.ewok.gds.journal.messages.XLogEntry) resource_);
    }
    if (resourceCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.ewok.gds.journal.messages.TxnAcctEntry) resource_);
    }
    if (resourceCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.ewok.gds.journal.messages.StorageEntry) resource_);
    }
    if (resourceCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.ewok.gds.journal.messages.HeapEntry) resource_);
    }
    if (resourceCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (io.ewok.gds.journal.messages.IndexEntry) resource_);
    }
    if (resourceCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (io.ewok.gds.journal.messages.CheckpointEntry) resource_);
    }
    if (resourceCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (io.ewok.gds.journal.messages.BlobEntry) resource_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ewok.gds.journal.messages.JournalEntry)) {
      return super.equals(obj);
    }
    io.ewok.gds.journal.messages.JournalEntry other = (io.ewok.gds.journal.messages.JournalEntry) obj;

    boolean result = true;
    result = result && getResourceCase().equals(
        other.getResourceCase());
    if (!result) return false;
    switch (resourceCase_) {
      case 1:
        result = result && getXlog()
            .equals(other.getXlog());
        break;
      case 2:
        result = result && getTxnAcct()
            .equals(other.getTxnAcct());
        break;
      case 3:
        result = result && getStorage()
            .equals(other.getStorage());
        break;
      case 4:
        result = result && getHeap()
            .equals(other.getHeap());
        break;
      case 5:
        result = result && getIndex()
            .equals(other.getIndex());
        break;
      case 6:
        result = result && getCheckpoint()
            .equals(other.getCheckpoint());
        break;
      case 7:
        result = result && getBlob()
            .equals(other.getBlob());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (resourceCase_) {
      case 1:
        hash = (37 * hash) + XLOG_FIELD_NUMBER;
        hash = (53 * hash) + getXlog().hashCode();
        break;
      case 2:
        hash = (37 * hash) + TXN_ACCT_FIELD_NUMBER;
        hash = (53 * hash) + getTxnAcct().hashCode();
        break;
      case 3:
        hash = (37 * hash) + STORAGE_FIELD_NUMBER;
        hash = (53 * hash) + getStorage().hashCode();
        break;
      case 4:
        hash = (37 * hash) + HEAP_FIELD_NUMBER;
        hash = (53 * hash) + getHeap().hashCode();
        break;
      case 5:
        hash = (37 * hash) + INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getIndex().hashCode();
        break;
      case 6:
        hash = (37 * hash) + CHECKPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getCheckpoint().hashCode();
        break;
      case 7:
        hash = (37 * hash) + BLOB_FIELD_NUMBER;
        hash = (53 * hash) + getBlob().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.JournalEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ewok.gds.journal.messages.JournalEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gds.wal.JournalEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gds.wal.JournalEntry)
      io.ewok.gds.journal.messages.JournalEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ewok.gds.journal.messages.JournalEntry.class, io.ewok.gds.journal.messages.JournalEntry.Builder.class);
    }

    // Construct using io.ewok.gds.journal.messages.JournalEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      resourceCase_ = 0;
      resource_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalEntry_descriptor;
    }

    public io.ewok.gds.journal.messages.JournalEntry getDefaultInstanceForType() {
      return io.ewok.gds.journal.messages.JournalEntry.getDefaultInstance();
    }

    public io.ewok.gds.journal.messages.JournalEntry build() {
      io.ewok.gds.journal.messages.JournalEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.ewok.gds.journal.messages.JournalEntry buildPartial() {
      io.ewok.gds.journal.messages.JournalEntry result = new io.ewok.gds.journal.messages.JournalEntry(this);
      if (resourceCase_ == 1) {
        if (xlogBuilder_ == null) {
          result.resource_ = resource_;
        } else {
          result.resource_ = xlogBuilder_.build();
        }
      }
      if (resourceCase_ == 2) {
        if (txnAcctBuilder_ == null) {
          result.resource_ = resource_;
        } else {
          result.resource_ = txnAcctBuilder_.build();
        }
      }
      if (resourceCase_ == 3) {
        if (storageBuilder_ == null) {
          result.resource_ = resource_;
        } else {
          result.resource_ = storageBuilder_.build();
        }
      }
      if (resourceCase_ == 4) {
        if (heapBuilder_ == null) {
          result.resource_ = resource_;
        } else {
          result.resource_ = heapBuilder_.build();
        }
      }
      if (resourceCase_ == 5) {
        if (indexBuilder_ == null) {
          result.resource_ = resource_;
        } else {
          result.resource_ = indexBuilder_.build();
        }
      }
      if (resourceCase_ == 6) {
        if (checkpointBuilder_ == null) {
          result.resource_ = resource_;
        } else {
          result.resource_ = checkpointBuilder_.build();
        }
      }
      if (resourceCase_ == 7) {
        if (blobBuilder_ == null) {
          result.resource_ = resource_;
        } else {
          result.resource_ = blobBuilder_.build();
        }
      }
      result.resourceCase_ = resourceCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ewok.gds.journal.messages.JournalEntry) {
        return mergeFrom((io.ewok.gds.journal.messages.JournalEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ewok.gds.journal.messages.JournalEntry other) {
      if (other == io.ewok.gds.journal.messages.JournalEntry.getDefaultInstance()) return this;
      switch (other.getResourceCase()) {
        case XLOG: {
          mergeXlog(other.getXlog());
          break;
        }
        case TXN_ACCT: {
          mergeTxnAcct(other.getTxnAcct());
          break;
        }
        case STORAGE: {
          mergeStorage(other.getStorage());
          break;
        }
        case HEAP: {
          mergeHeap(other.getHeap());
          break;
        }
        case INDEX: {
          mergeIndex(other.getIndex());
          break;
        }
        case CHECKPOINT: {
          mergeCheckpoint(other.getCheckpoint());
          break;
        }
        case BLOB: {
          mergeBlob(other.getBlob());
          break;
        }
        case RESOURCE_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.ewok.gds.journal.messages.JournalEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.ewok.gds.journal.messages.JournalEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int resourceCase_ = 0;
    private java.lang.Object resource_;
    public ResourceCase
        getResourceCase() {
      return ResourceCase.forNumber(
          resourceCase_);
    }

    public Builder clearResource() {
      resourceCase_ = 0;
      resource_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.XLogEntry, io.ewok.gds.journal.messages.XLogEntry.Builder, io.ewok.gds.journal.messages.XLogEntryOrBuilder> xlogBuilder_;
    /**
     * <code>.gds.wal.XLogEntry xlog = 1;</code>
     */
    public io.ewok.gds.journal.messages.XLogEntry getXlog() {
      if (xlogBuilder_ == null) {
        if (resourceCase_ == 1) {
          return (io.ewok.gds.journal.messages.XLogEntry) resource_;
        }
        return io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance();
      } else {
        if (resourceCase_ == 1) {
          return xlogBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.XLogEntry xlog = 1;</code>
     */
    public Builder setXlog(io.ewok.gds.journal.messages.XLogEntry value) {
      if (xlogBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        xlogBuilder_.setMessage(value);
      }
      resourceCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.XLogEntry xlog = 1;</code>
     */
    public Builder setXlog(
        io.ewok.gds.journal.messages.XLogEntry.Builder builderForValue) {
      if (xlogBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        xlogBuilder_.setMessage(builderForValue.build());
      }
      resourceCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.XLogEntry xlog = 1;</code>
     */
    public Builder mergeXlog(io.ewok.gds.journal.messages.XLogEntry value) {
      if (xlogBuilder_ == null) {
        if (resourceCase_ == 1 &&
            resource_ != io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance()) {
          resource_ = io.ewok.gds.journal.messages.XLogEntry.newBuilder((io.ewok.gds.journal.messages.XLogEntry) resource_)
              .mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        if (resourceCase_ == 1) {
          xlogBuilder_.mergeFrom(value);
        }
        xlogBuilder_.setMessage(value);
      }
      resourceCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.XLogEntry xlog = 1;</code>
     */
    public Builder clearXlog() {
      if (xlogBuilder_ == null) {
        if (resourceCase_ == 1) {
          resourceCase_ = 0;
          resource_ = null;
          onChanged();
        }
      } else {
        if (resourceCase_ == 1) {
          resourceCase_ = 0;
          resource_ = null;
        }
        xlogBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.XLogEntry xlog = 1;</code>
     */
    public io.ewok.gds.journal.messages.XLogEntry.Builder getXlogBuilder() {
      return getXlogFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.XLogEntry xlog = 1;</code>
     */
    public io.ewok.gds.journal.messages.XLogEntryOrBuilder getXlogOrBuilder() {
      if ((resourceCase_ == 1) && (xlogBuilder_ != null)) {
        return xlogBuilder_.getMessageOrBuilder();
      } else {
        if (resourceCase_ == 1) {
          return (io.ewok.gds.journal.messages.XLogEntry) resource_;
        }
        return io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.XLogEntry xlog = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.XLogEntry, io.ewok.gds.journal.messages.XLogEntry.Builder, io.ewok.gds.journal.messages.XLogEntryOrBuilder> 
        getXlogFieldBuilder() {
      if (xlogBuilder_ == null) {
        if (!(resourceCase_ == 1)) {
          resource_ = io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance();
        }
        xlogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.XLogEntry, io.ewok.gds.journal.messages.XLogEntry.Builder, io.ewok.gds.journal.messages.XLogEntryOrBuilder>(
                (io.ewok.gds.journal.messages.XLogEntry) resource_,
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      resourceCase_ = 1;
      onChanged();;
      return xlogBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.TxnAcctEntry, io.ewok.gds.journal.messages.TxnAcctEntry.Builder, io.ewok.gds.journal.messages.TxnAcctEntryOrBuilder> txnAcctBuilder_;
    /**
     * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
     */
    public io.ewok.gds.journal.messages.TxnAcctEntry getTxnAcct() {
      if (txnAcctBuilder_ == null) {
        if (resourceCase_ == 2) {
          return (io.ewok.gds.journal.messages.TxnAcctEntry) resource_;
        }
        return io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance();
      } else {
        if (resourceCase_ == 2) {
          return txnAcctBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
     */
    public Builder setTxnAcct(io.ewok.gds.journal.messages.TxnAcctEntry value) {
      if (txnAcctBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        txnAcctBuilder_.setMessage(value);
      }
      resourceCase_ = 2;
      return this;
    }
    /**
     * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
     */
    public Builder setTxnAcct(
        io.ewok.gds.journal.messages.TxnAcctEntry.Builder builderForValue) {
      if (txnAcctBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        txnAcctBuilder_.setMessage(builderForValue.build());
      }
      resourceCase_ = 2;
      return this;
    }
    /**
     * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
     */
    public Builder mergeTxnAcct(io.ewok.gds.journal.messages.TxnAcctEntry value) {
      if (txnAcctBuilder_ == null) {
        if (resourceCase_ == 2 &&
            resource_ != io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance()) {
          resource_ = io.ewok.gds.journal.messages.TxnAcctEntry.newBuilder((io.ewok.gds.journal.messages.TxnAcctEntry) resource_)
              .mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        if (resourceCase_ == 2) {
          txnAcctBuilder_.mergeFrom(value);
        }
        txnAcctBuilder_.setMessage(value);
      }
      resourceCase_ = 2;
      return this;
    }
    /**
     * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
     */
    public Builder clearTxnAcct() {
      if (txnAcctBuilder_ == null) {
        if (resourceCase_ == 2) {
          resourceCase_ = 0;
          resource_ = null;
          onChanged();
        }
      } else {
        if (resourceCase_ == 2) {
          resourceCase_ = 0;
          resource_ = null;
        }
        txnAcctBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
     */
    public io.ewok.gds.journal.messages.TxnAcctEntry.Builder getTxnAcctBuilder() {
      return getTxnAcctFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
     */
    public io.ewok.gds.journal.messages.TxnAcctEntryOrBuilder getTxnAcctOrBuilder() {
      if ((resourceCase_ == 2) && (txnAcctBuilder_ != null)) {
        return txnAcctBuilder_.getMessageOrBuilder();
      } else {
        if (resourceCase_ == 2) {
          return (io.ewok.gds.journal.messages.TxnAcctEntry) resource_;
        }
        return io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.TxnAcctEntry txn_acct = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.TxnAcctEntry, io.ewok.gds.journal.messages.TxnAcctEntry.Builder, io.ewok.gds.journal.messages.TxnAcctEntryOrBuilder> 
        getTxnAcctFieldBuilder() {
      if (txnAcctBuilder_ == null) {
        if (!(resourceCase_ == 2)) {
          resource_ = io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance();
        }
        txnAcctBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.TxnAcctEntry, io.ewok.gds.journal.messages.TxnAcctEntry.Builder, io.ewok.gds.journal.messages.TxnAcctEntryOrBuilder>(
                (io.ewok.gds.journal.messages.TxnAcctEntry) resource_,
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      resourceCase_ = 2;
      onChanged();;
      return txnAcctBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.StorageEntry, io.ewok.gds.journal.messages.StorageEntry.Builder, io.ewok.gds.journal.messages.StorageEntryOrBuilder> storageBuilder_;
    /**
     * <code>.gds.wal.StorageEntry storage = 3;</code>
     */
    public io.ewok.gds.journal.messages.StorageEntry getStorage() {
      if (storageBuilder_ == null) {
        if (resourceCase_ == 3) {
          return (io.ewok.gds.journal.messages.StorageEntry) resource_;
        }
        return io.ewok.gds.journal.messages.StorageEntry.getDefaultInstance();
      } else {
        if (resourceCase_ == 3) {
          return storageBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.StorageEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.StorageEntry storage = 3;</code>
     */
    public Builder setStorage(io.ewok.gds.journal.messages.StorageEntry value) {
      if (storageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        storageBuilder_.setMessage(value);
      }
      resourceCase_ = 3;
      return this;
    }
    /**
     * <code>.gds.wal.StorageEntry storage = 3;</code>
     */
    public Builder setStorage(
        io.ewok.gds.journal.messages.StorageEntry.Builder builderForValue) {
      if (storageBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        storageBuilder_.setMessage(builderForValue.build());
      }
      resourceCase_ = 3;
      return this;
    }
    /**
     * <code>.gds.wal.StorageEntry storage = 3;</code>
     */
    public Builder mergeStorage(io.ewok.gds.journal.messages.StorageEntry value) {
      if (storageBuilder_ == null) {
        if (resourceCase_ == 3 &&
            resource_ != io.ewok.gds.journal.messages.StorageEntry.getDefaultInstance()) {
          resource_ = io.ewok.gds.journal.messages.StorageEntry.newBuilder((io.ewok.gds.journal.messages.StorageEntry) resource_)
              .mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        if (resourceCase_ == 3) {
          storageBuilder_.mergeFrom(value);
        }
        storageBuilder_.setMessage(value);
      }
      resourceCase_ = 3;
      return this;
    }
    /**
     * <code>.gds.wal.StorageEntry storage = 3;</code>
     */
    public Builder clearStorage() {
      if (storageBuilder_ == null) {
        if (resourceCase_ == 3) {
          resourceCase_ = 0;
          resource_ = null;
          onChanged();
        }
      } else {
        if (resourceCase_ == 3) {
          resourceCase_ = 0;
          resource_ = null;
        }
        storageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.StorageEntry storage = 3;</code>
     */
    public io.ewok.gds.journal.messages.StorageEntry.Builder getStorageBuilder() {
      return getStorageFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.StorageEntry storage = 3;</code>
     */
    public io.ewok.gds.journal.messages.StorageEntryOrBuilder getStorageOrBuilder() {
      if ((resourceCase_ == 3) && (storageBuilder_ != null)) {
        return storageBuilder_.getMessageOrBuilder();
      } else {
        if (resourceCase_ == 3) {
          return (io.ewok.gds.journal.messages.StorageEntry) resource_;
        }
        return io.ewok.gds.journal.messages.StorageEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.StorageEntry storage = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.StorageEntry, io.ewok.gds.journal.messages.StorageEntry.Builder, io.ewok.gds.journal.messages.StorageEntryOrBuilder> 
        getStorageFieldBuilder() {
      if (storageBuilder_ == null) {
        if (!(resourceCase_ == 3)) {
          resource_ = io.ewok.gds.journal.messages.StorageEntry.getDefaultInstance();
        }
        storageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.StorageEntry, io.ewok.gds.journal.messages.StorageEntry.Builder, io.ewok.gds.journal.messages.StorageEntryOrBuilder>(
                (io.ewok.gds.journal.messages.StorageEntry) resource_,
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      resourceCase_ = 3;
      onChanged();;
      return storageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.HeapEntry, io.ewok.gds.journal.messages.HeapEntry.Builder, io.ewok.gds.journal.messages.HeapEntryOrBuilder> heapBuilder_;
    /**
     * <code>.gds.wal.HeapEntry heap = 4;</code>
     */
    public io.ewok.gds.journal.messages.HeapEntry getHeap() {
      if (heapBuilder_ == null) {
        if (resourceCase_ == 4) {
          return (io.ewok.gds.journal.messages.HeapEntry) resource_;
        }
        return io.ewok.gds.journal.messages.HeapEntry.getDefaultInstance();
      } else {
        if (resourceCase_ == 4) {
          return heapBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.HeapEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.HeapEntry heap = 4;</code>
     */
    public Builder setHeap(io.ewok.gds.journal.messages.HeapEntry value) {
      if (heapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        heapBuilder_.setMessage(value);
      }
      resourceCase_ = 4;
      return this;
    }
    /**
     * <code>.gds.wal.HeapEntry heap = 4;</code>
     */
    public Builder setHeap(
        io.ewok.gds.journal.messages.HeapEntry.Builder builderForValue) {
      if (heapBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        heapBuilder_.setMessage(builderForValue.build());
      }
      resourceCase_ = 4;
      return this;
    }
    /**
     * <code>.gds.wal.HeapEntry heap = 4;</code>
     */
    public Builder mergeHeap(io.ewok.gds.journal.messages.HeapEntry value) {
      if (heapBuilder_ == null) {
        if (resourceCase_ == 4 &&
            resource_ != io.ewok.gds.journal.messages.HeapEntry.getDefaultInstance()) {
          resource_ = io.ewok.gds.journal.messages.HeapEntry.newBuilder((io.ewok.gds.journal.messages.HeapEntry) resource_)
              .mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        if (resourceCase_ == 4) {
          heapBuilder_.mergeFrom(value);
        }
        heapBuilder_.setMessage(value);
      }
      resourceCase_ = 4;
      return this;
    }
    /**
     * <code>.gds.wal.HeapEntry heap = 4;</code>
     */
    public Builder clearHeap() {
      if (heapBuilder_ == null) {
        if (resourceCase_ == 4) {
          resourceCase_ = 0;
          resource_ = null;
          onChanged();
        }
      } else {
        if (resourceCase_ == 4) {
          resourceCase_ = 0;
          resource_ = null;
        }
        heapBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.HeapEntry heap = 4;</code>
     */
    public io.ewok.gds.journal.messages.HeapEntry.Builder getHeapBuilder() {
      return getHeapFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.HeapEntry heap = 4;</code>
     */
    public io.ewok.gds.journal.messages.HeapEntryOrBuilder getHeapOrBuilder() {
      if ((resourceCase_ == 4) && (heapBuilder_ != null)) {
        return heapBuilder_.getMessageOrBuilder();
      } else {
        if (resourceCase_ == 4) {
          return (io.ewok.gds.journal.messages.HeapEntry) resource_;
        }
        return io.ewok.gds.journal.messages.HeapEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.HeapEntry heap = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.HeapEntry, io.ewok.gds.journal.messages.HeapEntry.Builder, io.ewok.gds.journal.messages.HeapEntryOrBuilder> 
        getHeapFieldBuilder() {
      if (heapBuilder_ == null) {
        if (!(resourceCase_ == 4)) {
          resource_ = io.ewok.gds.journal.messages.HeapEntry.getDefaultInstance();
        }
        heapBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.HeapEntry, io.ewok.gds.journal.messages.HeapEntry.Builder, io.ewok.gds.journal.messages.HeapEntryOrBuilder>(
                (io.ewok.gds.journal.messages.HeapEntry) resource_,
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      resourceCase_ = 4;
      onChanged();;
      return heapBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.IndexEntry, io.ewok.gds.journal.messages.IndexEntry.Builder, io.ewok.gds.journal.messages.IndexEntryOrBuilder> indexBuilder_;
    /**
     * <code>.gds.wal.IndexEntry index = 5;</code>
     */
    public io.ewok.gds.journal.messages.IndexEntry getIndex() {
      if (indexBuilder_ == null) {
        if (resourceCase_ == 5) {
          return (io.ewok.gds.journal.messages.IndexEntry) resource_;
        }
        return io.ewok.gds.journal.messages.IndexEntry.getDefaultInstance();
      } else {
        if (resourceCase_ == 5) {
          return indexBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.IndexEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.IndexEntry index = 5;</code>
     */
    public Builder setIndex(io.ewok.gds.journal.messages.IndexEntry value) {
      if (indexBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        indexBuilder_.setMessage(value);
      }
      resourceCase_ = 5;
      return this;
    }
    /**
     * <code>.gds.wal.IndexEntry index = 5;</code>
     */
    public Builder setIndex(
        io.ewok.gds.journal.messages.IndexEntry.Builder builderForValue) {
      if (indexBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        indexBuilder_.setMessage(builderForValue.build());
      }
      resourceCase_ = 5;
      return this;
    }
    /**
     * <code>.gds.wal.IndexEntry index = 5;</code>
     */
    public Builder mergeIndex(io.ewok.gds.journal.messages.IndexEntry value) {
      if (indexBuilder_ == null) {
        if (resourceCase_ == 5 &&
            resource_ != io.ewok.gds.journal.messages.IndexEntry.getDefaultInstance()) {
          resource_ = io.ewok.gds.journal.messages.IndexEntry.newBuilder((io.ewok.gds.journal.messages.IndexEntry) resource_)
              .mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        if (resourceCase_ == 5) {
          indexBuilder_.mergeFrom(value);
        }
        indexBuilder_.setMessage(value);
      }
      resourceCase_ = 5;
      return this;
    }
    /**
     * <code>.gds.wal.IndexEntry index = 5;</code>
     */
    public Builder clearIndex() {
      if (indexBuilder_ == null) {
        if (resourceCase_ == 5) {
          resourceCase_ = 0;
          resource_ = null;
          onChanged();
        }
      } else {
        if (resourceCase_ == 5) {
          resourceCase_ = 0;
          resource_ = null;
        }
        indexBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.IndexEntry index = 5;</code>
     */
    public io.ewok.gds.journal.messages.IndexEntry.Builder getIndexBuilder() {
      return getIndexFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.IndexEntry index = 5;</code>
     */
    public io.ewok.gds.journal.messages.IndexEntryOrBuilder getIndexOrBuilder() {
      if ((resourceCase_ == 5) && (indexBuilder_ != null)) {
        return indexBuilder_.getMessageOrBuilder();
      } else {
        if (resourceCase_ == 5) {
          return (io.ewok.gds.journal.messages.IndexEntry) resource_;
        }
        return io.ewok.gds.journal.messages.IndexEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.IndexEntry index = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.IndexEntry, io.ewok.gds.journal.messages.IndexEntry.Builder, io.ewok.gds.journal.messages.IndexEntryOrBuilder> 
        getIndexFieldBuilder() {
      if (indexBuilder_ == null) {
        if (!(resourceCase_ == 5)) {
          resource_ = io.ewok.gds.journal.messages.IndexEntry.getDefaultInstance();
        }
        indexBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.IndexEntry, io.ewok.gds.journal.messages.IndexEntry.Builder, io.ewok.gds.journal.messages.IndexEntryOrBuilder>(
                (io.ewok.gds.journal.messages.IndexEntry) resource_,
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      resourceCase_ = 5;
      onChanged();;
      return indexBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.CheckpointEntry, io.ewok.gds.journal.messages.CheckpointEntry.Builder, io.ewok.gds.journal.messages.CheckpointEntryOrBuilder> checkpointBuilder_;
    /**
     * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
     */
    public io.ewok.gds.journal.messages.CheckpointEntry getCheckpoint() {
      if (checkpointBuilder_ == null) {
        if (resourceCase_ == 6) {
          return (io.ewok.gds.journal.messages.CheckpointEntry) resource_;
        }
        return io.ewok.gds.journal.messages.CheckpointEntry.getDefaultInstance();
      } else {
        if (resourceCase_ == 6) {
          return checkpointBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.CheckpointEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
     */
    public Builder setCheckpoint(io.ewok.gds.journal.messages.CheckpointEntry value) {
      if (checkpointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        checkpointBuilder_.setMessage(value);
      }
      resourceCase_ = 6;
      return this;
    }
    /**
     * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
     */
    public Builder setCheckpoint(
        io.ewok.gds.journal.messages.CheckpointEntry.Builder builderForValue) {
      if (checkpointBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        checkpointBuilder_.setMessage(builderForValue.build());
      }
      resourceCase_ = 6;
      return this;
    }
    /**
     * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
     */
    public Builder mergeCheckpoint(io.ewok.gds.journal.messages.CheckpointEntry value) {
      if (checkpointBuilder_ == null) {
        if (resourceCase_ == 6 &&
            resource_ != io.ewok.gds.journal.messages.CheckpointEntry.getDefaultInstance()) {
          resource_ = io.ewok.gds.journal.messages.CheckpointEntry.newBuilder((io.ewok.gds.journal.messages.CheckpointEntry) resource_)
              .mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        if (resourceCase_ == 6) {
          checkpointBuilder_.mergeFrom(value);
        }
        checkpointBuilder_.setMessage(value);
      }
      resourceCase_ = 6;
      return this;
    }
    /**
     * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
     */
    public Builder clearCheckpoint() {
      if (checkpointBuilder_ == null) {
        if (resourceCase_ == 6) {
          resourceCase_ = 0;
          resource_ = null;
          onChanged();
        }
      } else {
        if (resourceCase_ == 6) {
          resourceCase_ = 0;
          resource_ = null;
        }
        checkpointBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
     */
    public io.ewok.gds.journal.messages.CheckpointEntry.Builder getCheckpointBuilder() {
      return getCheckpointFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
     */
    public io.ewok.gds.journal.messages.CheckpointEntryOrBuilder getCheckpointOrBuilder() {
      if ((resourceCase_ == 6) && (checkpointBuilder_ != null)) {
        return checkpointBuilder_.getMessageOrBuilder();
      } else {
        if (resourceCase_ == 6) {
          return (io.ewok.gds.journal.messages.CheckpointEntry) resource_;
        }
        return io.ewok.gds.journal.messages.CheckpointEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.CheckpointEntry checkpoint = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.CheckpointEntry, io.ewok.gds.journal.messages.CheckpointEntry.Builder, io.ewok.gds.journal.messages.CheckpointEntryOrBuilder> 
        getCheckpointFieldBuilder() {
      if (checkpointBuilder_ == null) {
        if (!(resourceCase_ == 6)) {
          resource_ = io.ewok.gds.journal.messages.CheckpointEntry.getDefaultInstance();
        }
        checkpointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.CheckpointEntry, io.ewok.gds.journal.messages.CheckpointEntry.Builder, io.ewok.gds.journal.messages.CheckpointEntryOrBuilder>(
                (io.ewok.gds.journal.messages.CheckpointEntry) resource_,
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      resourceCase_ = 6;
      onChanged();;
      return checkpointBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.BlobEntry, io.ewok.gds.journal.messages.BlobEntry.Builder, io.ewok.gds.journal.messages.BlobEntryOrBuilder> blobBuilder_;
    /**
     * <code>.gds.wal.BlobEntry blob = 7;</code>
     */
    public io.ewok.gds.journal.messages.BlobEntry getBlob() {
      if (blobBuilder_ == null) {
        if (resourceCase_ == 7) {
          return (io.ewok.gds.journal.messages.BlobEntry) resource_;
        }
        return io.ewok.gds.journal.messages.BlobEntry.getDefaultInstance();
      } else {
        if (resourceCase_ == 7) {
          return blobBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.BlobEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.BlobEntry blob = 7;</code>
     */
    public Builder setBlob(io.ewok.gds.journal.messages.BlobEntry value) {
      if (blobBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resource_ = value;
        onChanged();
      } else {
        blobBuilder_.setMessage(value);
      }
      resourceCase_ = 7;
      return this;
    }
    /**
     * <code>.gds.wal.BlobEntry blob = 7;</code>
     */
    public Builder setBlob(
        io.ewok.gds.journal.messages.BlobEntry.Builder builderForValue) {
      if (blobBuilder_ == null) {
        resource_ = builderForValue.build();
        onChanged();
      } else {
        blobBuilder_.setMessage(builderForValue.build());
      }
      resourceCase_ = 7;
      return this;
    }
    /**
     * <code>.gds.wal.BlobEntry blob = 7;</code>
     */
    public Builder mergeBlob(io.ewok.gds.journal.messages.BlobEntry value) {
      if (blobBuilder_ == null) {
        if (resourceCase_ == 7 &&
            resource_ != io.ewok.gds.journal.messages.BlobEntry.getDefaultInstance()) {
          resource_ = io.ewok.gds.journal.messages.BlobEntry.newBuilder((io.ewok.gds.journal.messages.BlobEntry) resource_)
              .mergeFrom(value).buildPartial();
        } else {
          resource_ = value;
        }
        onChanged();
      } else {
        if (resourceCase_ == 7) {
          blobBuilder_.mergeFrom(value);
        }
        blobBuilder_.setMessage(value);
      }
      resourceCase_ = 7;
      return this;
    }
    /**
     * <code>.gds.wal.BlobEntry blob = 7;</code>
     */
    public Builder clearBlob() {
      if (blobBuilder_ == null) {
        if (resourceCase_ == 7) {
          resourceCase_ = 0;
          resource_ = null;
          onChanged();
        }
      } else {
        if (resourceCase_ == 7) {
          resourceCase_ = 0;
          resource_ = null;
        }
        blobBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.BlobEntry blob = 7;</code>
     */
    public io.ewok.gds.journal.messages.BlobEntry.Builder getBlobBuilder() {
      return getBlobFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.BlobEntry blob = 7;</code>
     */
    public io.ewok.gds.journal.messages.BlobEntryOrBuilder getBlobOrBuilder() {
      if ((resourceCase_ == 7) && (blobBuilder_ != null)) {
        return blobBuilder_.getMessageOrBuilder();
      } else {
        if (resourceCase_ == 7) {
          return (io.ewok.gds.journal.messages.BlobEntry) resource_;
        }
        return io.ewok.gds.journal.messages.BlobEntry.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.BlobEntry blob = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.BlobEntry, io.ewok.gds.journal.messages.BlobEntry.Builder, io.ewok.gds.journal.messages.BlobEntryOrBuilder> 
        getBlobFieldBuilder() {
      if (blobBuilder_ == null) {
        if (!(resourceCase_ == 7)) {
          resource_ = io.ewok.gds.journal.messages.BlobEntry.getDefaultInstance();
        }
        blobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.BlobEntry, io.ewok.gds.journal.messages.BlobEntry.Builder, io.ewok.gds.journal.messages.BlobEntryOrBuilder>(
                (io.ewok.gds.journal.messages.BlobEntry) resource_,
                getParentForChildren(),
                isClean());
        resource_ = null;
      }
      resourceCase_ = 7;
      onChanged();;
      return blobBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:gds.wal.JournalEntry)
  }

  // @@protoc_insertion_point(class_scope:gds.wal.JournalEntry)
  private static final io.ewok.gds.journal.messages.JournalEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ewok.gds.journal.messages.JournalEntry();
  }

  public static io.ewok.gds.journal.messages.JournalEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JournalEntry>
      PARSER = new com.google.protobuf.AbstractParser<JournalEntry>() {
    public JournalEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new JournalEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JournalEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JournalEntry> getParserForType() {
    return PARSER;
  }

  public io.ewok.gds.journal.messages.JournalEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

