// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: journal.proto

package io.ewok.gds.journal.messages;

/**
 * Protobuf type {@code gds.wal.JournalRecord}
 */
public  final class JournalRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gds.wal.JournalRecord)
    JournalRecordOrBuilder {
  // Use JournalRecord.newBuilder() to construct.
  private JournalRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JournalRecord() {
    entry_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private JournalRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              entry_ = new java.util.ArrayList<io.ewok.gds.journal.messages.JournalEntry>();
              mutable_bitField0_ |= 0x00000001;
            }
            entry_.add(
                input.readMessage(io.ewok.gds.journal.messages.JournalEntry.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        entry_ = java.util.Collections.unmodifiableList(entry_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalRecord_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ewok.gds.journal.messages.JournalRecord.class, io.ewok.gds.journal.messages.JournalRecord.Builder.class);
  }

  public static final int ENTRY_FIELD_NUMBER = 1;
  private java.util.List<io.ewok.gds.journal.messages.JournalEntry> entry_;
  /**
   * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
   */
  public java.util.List<io.ewok.gds.journal.messages.JournalEntry> getEntryList() {
    return entry_;
  }
  /**
   * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
   */
  public java.util.List<? extends io.ewok.gds.journal.messages.JournalEntryOrBuilder> 
      getEntryOrBuilderList() {
    return entry_;
  }
  /**
   * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
   */
  public int getEntryCount() {
    return entry_.size();
  }
  /**
   * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
   */
  public io.ewok.gds.journal.messages.JournalEntry getEntry(int index) {
    return entry_.get(index);
  }
  /**
   * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
   */
  public io.ewok.gds.journal.messages.JournalEntryOrBuilder getEntryOrBuilder(
      int index) {
    return entry_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entry_.size(); i++) {
      output.writeMessage(1, entry_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entry_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entry_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ewok.gds.journal.messages.JournalRecord)) {
      return super.equals(obj);
    }
    io.ewok.gds.journal.messages.JournalRecord other = (io.ewok.gds.journal.messages.JournalRecord) obj;

    boolean result = true;
    result = result && getEntryList()
        .equals(other.getEntryList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntryCount() > 0) {
      hash = (37 * hash) + ENTRY_FIELD_NUMBER;
      hash = (53 * hash) + getEntryList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.JournalRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ewok.gds.journal.messages.JournalRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gds.wal.JournalRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gds.wal.JournalRecord)
      io.ewok.gds.journal.messages.JournalRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ewok.gds.journal.messages.JournalRecord.class, io.ewok.gds.journal.messages.JournalRecord.Builder.class);
    }

    // Construct using io.ewok.gds.journal.messages.JournalRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEntryFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (entryBuilder_ == null) {
        entry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        entryBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_JournalRecord_descriptor;
    }

    public io.ewok.gds.journal.messages.JournalRecord getDefaultInstanceForType() {
      return io.ewok.gds.journal.messages.JournalRecord.getDefaultInstance();
    }

    public io.ewok.gds.journal.messages.JournalRecord build() {
      io.ewok.gds.journal.messages.JournalRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.ewok.gds.journal.messages.JournalRecord buildPartial() {
      io.ewok.gds.journal.messages.JournalRecord result = new io.ewok.gds.journal.messages.JournalRecord(this);
      int from_bitField0_ = bitField0_;
      if (entryBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entry_ = entry_;
      } else {
        result.entry_ = entryBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ewok.gds.journal.messages.JournalRecord) {
        return mergeFrom((io.ewok.gds.journal.messages.JournalRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ewok.gds.journal.messages.JournalRecord other) {
      if (other == io.ewok.gds.journal.messages.JournalRecord.getDefaultInstance()) return this;
      if (entryBuilder_ == null) {
        if (!other.entry_.isEmpty()) {
          if (entry_.isEmpty()) {
            entry_ = other.entry_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntryIsMutable();
            entry_.addAll(other.entry_);
          }
          onChanged();
        }
      } else {
        if (!other.entry_.isEmpty()) {
          if (entryBuilder_.isEmpty()) {
            entryBuilder_.dispose();
            entryBuilder_ = null;
            entry_ = other.entry_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entryBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntryFieldBuilder() : null;
          } else {
            entryBuilder_.addAllMessages(other.entry_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.ewok.gds.journal.messages.JournalRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.ewok.gds.journal.messages.JournalRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.ewok.gds.journal.messages.JournalEntry> entry_ =
      java.util.Collections.emptyList();
    private void ensureEntryIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        entry_ = new java.util.ArrayList<io.ewok.gds.journal.messages.JournalEntry>(entry_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.ewok.gds.journal.messages.JournalEntry, io.ewok.gds.journal.messages.JournalEntry.Builder, io.ewok.gds.journal.messages.JournalEntryOrBuilder> entryBuilder_;

    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public java.util.List<io.ewok.gds.journal.messages.JournalEntry> getEntryList() {
      if (entryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entry_);
      } else {
        return entryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public int getEntryCount() {
      if (entryBuilder_ == null) {
        return entry_.size();
      } else {
        return entryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public io.ewok.gds.journal.messages.JournalEntry getEntry(int index) {
      if (entryBuilder_ == null) {
        return entry_.get(index);
      } else {
        return entryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder setEntry(
        int index, io.ewok.gds.journal.messages.JournalEntry value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.set(index, value);
        onChanged();
      } else {
        entryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder setEntry(
        int index, io.ewok.gds.journal.messages.JournalEntry.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.set(index, builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder addEntry(io.ewok.gds.journal.messages.JournalEntry value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(value);
        onChanged();
      } else {
        entryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder addEntry(
        int index, io.ewok.gds.journal.messages.JournalEntry value) {
      if (entryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntryIsMutable();
        entry_.add(index, value);
        onChanged();
      } else {
        entryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder addEntry(
        io.ewok.gds.journal.messages.JournalEntry.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.add(builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder addEntry(
        int index, io.ewok.gds.journal.messages.JournalEntry.Builder builderForValue) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.add(index, builderForValue.build());
        onChanged();
      } else {
        entryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder addAllEntry(
        java.lang.Iterable<? extends io.ewok.gds.journal.messages.JournalEntry> values) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entry_);
        onChanged();
      } else {
        entryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder clearEntry() {
      if (entryBuilder_ == null) {
        entry_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public Builder removeEntry(int index) {
      if (entryBuilder_ == null) {
        ensureEntryIsMutable();
        entry_.remove(index);
        onChanged();
      } else {
        entryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public io.ewok.gds.journal.messages.JournalEntry.Builder getEntryBuilder(
        int index) {
      return getEntryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public io.ewok.gds.journal.messages.JournalEntryOrBuilder getEntryOrBuilder(
        int index) {
      if (entryBuilder_ == null) {
        return entry_.get(index);  } else {
        return entryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public java.util.List<? extends io.ewok.gds.journal.messages.JournalEntryOrBuilder> 
         getEntryOrBuilderList() {
      if (entryBuilder_ != null) {
        return entryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entry_);
      }
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public io.ewok.gds.journal.messages.JournalEntry.Builder addEntryBuilder() {
      return getEntryFieldBuilder().addBuilder(
          io.ewok.gds.journal.messages.JournalEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public io.ewok.gds.journal.messages.JournalEntry.Builder addEntryBuilder(
        int index) {
      return getEntryFieldBuilder().addBuilder(
          index, io.ewok.gds.journal.messages.JournalEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .gds.wal.JournalEntry entry = 1;</code>
     */
    public java.util.List<io.ewok.gds.journal.messages.JournalEntry.Builder> 
         getEntryBuilderList() {
      return getEntryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.ewok.gds.journal.messages.JournalEntry, io.ewok.gds.journal.messages.JournalEntry.Builder, io.ewok.gds.journal.messages.JournalEntryOrBuilder> 
        getEntryFieldBuilder() {
      if (entryBuilder_ == null) {
        entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.ewok.gds.journal.messages.JournalEntry, io.ewok.gds.journal.messages.JournalEntry.Builder, io.ewok.gds.journal.messages.JournalEntryOrBuilder>(
                entry_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        entry_ = null;
      }
      return entryBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:gds.wal.JournalRecord)
  }

  // @@protoc_insertion_point(class_scope:gds.wal.JournalRecord)
  private static final io.ewok.gds.journal.messages.JournalRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ewok.gds.journal.messages.JournalRecord();
  }

  public static io.ewok.gds.journal.messages.JournalRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JournalRecord>
      PARSER = new com.google.protobuf.AbstractParser<JournalRecord>() {
    public JournalRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new JournalRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JournalRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JournalRecord> getParserForType() {
    return PARSER;
  }

  public io.ewok.gds.journal.messages.JournalRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

