// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: journal.proto

package io.ewok.gds.journal.messages;

public final class JournalProto {
  private JournalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_JournalRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_JournalRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_JournalEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_JournalEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_XLogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_XLogEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_XLogEntry_Checkpoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_XLogEntry_Checkpoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_TxnBegin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_TxnBegin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_TxnCommit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_TxnCommit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_TxnAbort_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_TxnAbort_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_TxnAcctEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_TxnAcctEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_StorageCreate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_StorageCreate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_StorageEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_StorageEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_HeapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_HeapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_IndexEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_IndexEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_CheckpointEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_CheckpointEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gds_wal_BlobEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gds_wal_BlobEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rjournal.proto\022\007gds.wal\032\031google/protobu" +
      "f/any.proto\"5\n\rJournalRecord\022$\n\005entry\030\001 " +
      "\003(\0132\025.gds.wal.JournalEntry\"\261\002\n\014JournalEn" +
      "try\022\"\n\004xlog\030\001 \001(\0132\022.gds.wal.XLogEntryH\000\022" +
      ")\n\010txn_acct\030\002 \001(\0132\025.gds.wal.TxnAcctEntry" +
      "H\000\022(\n\007storage\030\003 \001(\0132\025.gds.wal.StorageEnt" +
      "ryH\000\022\"\n\004heap\030\004 \001(\0132\022.gds.wal.HeapEntryH\000" +
      "\022$\n\005index\030\005 \001(\0132\023.gds.wal.IndexEntryH\000\022." +
      "\n\ncheckpoint\030\006 \001(\0132\030.gds.wal.CheckpointE" +
      "ntryH\000\022\"\n\004blob\030\007 \001(\0132\022.gds.wal.BlobEntry",
      "H\000B\n\n\010resource\"Y\n\tXLogEntry\0223\n\ncheckpoin" +
      "t\030\001 \001(\0132\035.gds.wal.XLogEntry.CheckpointH\000" +
      "\032\014\n\nCheckpointB\t\n\007payload\"\032\n\010TxnBegin\022\016\n" +
      "\006txn_id\030\001 \001(\r\"\033\n\tTxnCommit\022\016\n\006txn_id\030\001 \001" +
      "(\r\"\032\n\010TxnAbort\022\016\n\006txn_id\030\001 \001(\r\"\223\001\n\014TxnAc" +
      "ctEntry\022&\n\ttxn_begin\030\001 \001(\0132\021.gds.wal.Txn" +
      "BeginH\000\022(\n\ntxn_commit\030\002 \001(\0132\022.gds.wal.Tx" +
      "nCommitH\000\022&\n\ttxn_abort\030\003 \001(\0132\021.gds.wal.T" +
      "xnAbortH\000B\t\n\007payload\"\017\n\rStorageCreate\"C\n" +
      "\014StorageEntry\022(\n\006create\030\001 \001(\0132\026.gds.wal.",
      "StorageCreateH\000B\t\n\007payload\"@\n\tHeapEntry\022" +
      "(\n\006create\030\001 \001(\0132\026.gds.wal.StorageCreateH" +
      "\000B\t\n\007payload\"A\n\nIndexEntry\022(\n\006create\030\001 \001" +
      "(\0132\026.gds.wal.StorageCreateH\000B\t\n\007payload\"" +
      "F\n\017CheckpointEntry\022(\n\006create\030\001 \001(\0132\026.gds" +
      ".wal.StorageCreateH\000B\t\n\007payload\"@\n\tBlobE" +
      "ntry\022(\n\006create\030\001 \001(\0132\026.gds.wal.StorageCr" +
      "eateH\000B\t\n\007payloadB.\n\034io.ewok.gds.journal" +
      ".messagesB\014JournalProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_gds_wal_JournalRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gds_wal_JournalRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_JournalRecord_descriptor,
        new java.lang.String[] { "Entry", });
    internal_static_gds_wal_JournalEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gds_wal_JournalEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_JournalEntry_descriptor,
        new java.lang.String[] { "Xlog", "TxnAcct", "Storage", "Heap", "Index", "Checkpoint", "Blob", "Resource", });
    internal_static_gds_wal_XLogEntry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gds_wal_XLogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_XLogEntry_descriptor,
        new java.lang.String[] { "Checkpoint", "Payload", });
    internal_static_gds_wal_XLogEntry_Checkpoint_descriptor =
      internal_static_gds_wal_XLogEntry_descriptor.getNestedTypes().get(0);
    internal_static_gds_wal_XLogEntry_Checkpoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_XLogEntry_Checkpoint_descriptor,
        new java.lang.String[] { });
    internal_static_gds_wal_TxnBegin_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gds_wal_TxnBegin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_TxnBegin_descriptor,
        new java.lang.String[] { "TxnId", });
    internal_static_gds_wal_TxnCommit_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gds_wal_TxnCommit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_TxnCommit_descriptor,
        new java.lang.String[] { "TxnId", });
    internal_static_gds_wal_TxnAbort_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gds_wal_TxnAbort_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_TxnAbort_descriptor,
        new java.lang.String[] { "TxnId", });
    internal_static_gds_wal_TxnAcctEntry_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_gds_wal_TxnAcctEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_TxnAcctEntry_descriptor,
        new java.lang.String[] { "TxnBegin", "TxnCommit", "TxnAbort", "Payload", });
    internal_static_gds_wal_StorageCreate_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_gds_wal_StorageCreate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_StorageCreate_descriptor,
        new java.lang.String[] { });
    internal_static_gds_wal_StorageEntry_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_gds_wal_StorageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_StorageEntry_descriptor,
        new java.lang.String[] { "Create", "Payload", });
    internal_static_gds_wal_HeapEntry_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_gds_wal_HeapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_HeapEntry_descriptor,
        new java.lang.String[] { "Create", "Payload", });
    internal_static_gds_wal_IndexEntry_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_gds_wal_IndexEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_IndexEntry_descriptor,
        new java.lang.String[] { "Create", "Payload", });
    internal_static_gds_wal_CheckpointEntry_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_gds_wal_CheckpointEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_CheckpointEntry_descriptor,
        new java.lang.String[] { "Create", "Payload", });
    internal_static_gds_wal_BlobEntry_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_gds_wal_BlobEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gds_wal_BlobEntry_descriptor,
        new java.lang.String[] { "Create", "Payload", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
