// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: journal.proto

package io.ewok.gds.journal.messages;

public interface StorageCreateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gds.wal.StorageCreate)
    com.google.protobuf.MessageOrBuilder {
}
