// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: journal.proto

package io.ewok.gds.journal.messages;

/**
 * Protobuf type {@code gds.wal.TxnAcctEntry}
 */
public  final class TxnAcctEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gds.wal.TxnAcctEntry)
    TxnAcctEntryOrBuilder {
  // Use TxnAcctEntry.newBuilder() to construct.
  private TxnAcctEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TxnAcctEntry() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TxnAcctEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.ewok.gds.journal.messages.TxnBegin.Builder subBuilder = null;
            if (payloadCase_ == 1) {
              subBuilder = ((io.ewok.gds.journal.messages.TxnBegin) payload_).toBuilder();
            }
            payload_ =
                input.readMessage(io.ewok.gds.journal.messages.TxnBegin.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.TxnBegin) payload_);
              payload_ = subBuilder.buildPartial();
            }
            payloadCase_ = 1;
            break;
          }
          case 18: {
            io.ewok.gds.journal.messages.TxnCommit.Builder subBuilder = null;
            if (payloadCase_ == 2) {
              subBuilder = ((io.ewok.gds.journal.messages.TxnCommit) payload_).toBuilder();
            }
            payload_ =
                input.readMessage(io.ewok.gds.journal.messages.TxnCommit.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.TxnCommit) payload_);
              payload_ = subBuilder.buildPartial();
            }
            payloadCase_ = 2;
            break;
          }
          case 26: {
            io.ewok.gds.journal.messages.TxnAbort.Builder subBuilder = null;
            if (payloadCase_ == 3) {
              subBuilder = ((io.ewok.gds.journal.messages.TxnAbort) payload_).toBuilder();
            }
            payload_ =
                input.readMessage(io.ewok.gds.journal.messages.TxnAbort.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.TxnAbort) payload_);
              payload_ = subBuilder.buildPartial();
            }
            payloadCase_ = 3;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_TxnAcctEntry_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_TxnAcctEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ewok.gds.journal.messages.TxnAcctEntry.class, io.ewok.gds.journal.messages.TxnAcctEntry.Builder.class);
  }

  private int payloadCase_ = 0;
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite {
    TXN_BEGIN(1),
    TXN_COMMIT(2),
    TXN_ABORT(3),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1: return TXN_BEGIN;
        case 2: return TXN_COMMIT;
        case 3: return TXN_ABORT;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TXN_BEGIN_FIELD_NUMBER = 1;
  /**
   * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
   */
  public io.ewok.gds.journal.messages.TxnBegin getTxnBegin() {
    if (payloadCase_ == 1) {
       return (io.ewok.gds.journal.messages.TxnBegin) payload_;
    }
    return io.ewok.gds.journal.messages.TxnBegin.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
   */
  public io.ewok.gds.journal.messages.TxnBeginOrBuilder getTxnBeginOrBuilder() {
    if (payloadCase_ == 1) {
       return (io.ewok.gds.journal.messages.TxnBegin) payload_;
    }
    return io.ewok.gds.journal.messages.TxnBegin.getDefaultInstance();
  }

  public static final int TXN_COMMIT_FIELD_NUMBER = 2;
  /**
   * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
   */
  public io.ewok.gds.journal.messages.TxnCommit getTxnCommit() {
    if (payloadCase_ == 2) {
       return (io.ewok.gds.journal.messages.TxnCommit) payload_;
    }
    return io.ewok.gds.journal.messages.TxnCommit.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
   */
  public io.ewok.gds.journal.messages.TxnCommitOrBuilder getTxnCommitOrBuilder() {
    if (payloadCase_ == 2) {
       return (io.ewok.gds.journal.messages.TxnCommit) payload_;
    }
    return io.ewok.gds.journal.messages.TxnCommit.getDefaultInstance();
  }

  public static final int TXN_ABORT_FIELD_NUMBER = 3;
  /**
   * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
   */
  public io.ewok.gds.journal.messages.TxnAbort getTxnAbort() {
    if (payloadCase_ == 3) {
       return (io.ewok.gds.journal.messages.TxnAbort) payload_;
    }
    return io.ewok.gds.journal.messages.TxnAbort.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
   */
  public io.ewok.gds.journal.messages.TxnAbortOrBuilder getTxnAbortOrBuilder() {
    if (payloadCase_ == 3) {
       return (io.ewok.gds.journal.messages.TxnAbort) payload_;
    }
    return io.ewok.gds.journal.messages.TxnAbort.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (io.ewok.gds.journal.messages.TxnBegin) payload_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (io.ewok.gds.journal.messages.TxnCommit) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (io.ewok.gds.journal.messages.TxnAbort) payload_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.ewok.gds.journal.messages.TxnBegin) payload_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.ewok.gds.journal.messages.TxnCommit) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.ewok.gds.journal.messages.TxnAbort) payload_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ewok.gds.journal.messages.TxnAcctEntry)) {
      return super.equals(obj);
    }
    io.ewok.gds.journal.messages.TxnAcctEntry other = (io.ewok.gds.journal.messages.TxnAcctEntry) obj;

    boolean result = true;
    result = result && getPayloadCase().equals(
        other.getPayloadCase());
    if (!result) return false;
    switch (payloadCase_) {
      case 1:
        result = result && getTxnBegin()
            .equals(other.getTxnBegin());
        break;
      case 2:
        result = result && getTxnCommit()
            .equals(other.getTxnCommit());
        break;
      case 3:
        result = result && getTxnAbort()
            .equals(other.getTxnAbort());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + TXN_BEGIN_FIELD_NUMBER;
        hash = (53 * hash) + getTxnBegin().hashCode();
        break;
      case 2:
        hash = (37 * hash) + TXN_COMMIT_FIELD_NUMBER;
        hash = (53 * hash) + getTxnCommit().hashCode();
        break;
      case 3:
        hash = (37 * hash) + TXN_ABORT_FIELD_NUMBER;
        hash = (53 * hash) + getTxnAbort().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.TxnAcctEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ewok.gds.journal.messages.TxnAcctEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gds.wal.TxnAcctEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gds.wal.TxnAcctEntry)
      io.ewok.gds.journal.messages.TxnAcctEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_TxnAcctEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_TxnAcctEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ewok.gds.journal.messages.TxnAcctEntry.class, io.ewok.gds.journal.messages.TxnAcctEntry.Builder.class);
    }

    // Construct using io.ewok.gds.journal.messages.TxnAcctEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_TxnAcctEntry_descriptor;
    }

    public io.ewok.gds.journal.messages.TxnAcctEntry getDefaultInstanceForType() {
      return io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance();
    }

    public io.ewok.gds.journal.messages.TxnAcctEntry build() {
      io.ewok.gds.journal.messages.TxnAcctEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.ewok.gds.journal.messages.TxnAcctEntry buildPartial() {
      io.ewok.gds.journal.messages.TxnAcctEntry result = new io.ewok.gds.journal.messages.TxnAcctEntry(this);
      if (payloadCase_ == 1) {
        if (txnBeginBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = txnBeginBuilder_.build();
        }
      }
      if (payloadCase_ == 2) {
        if (txnCommitBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = txnCommitBuilder_.build();
        }
      }
      if (payloadCase_ == 3) {
        if (txnAbortBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = txnAbortBuilder_.build();
        }
      }
      result.payloadCase_ = payloadCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ewok.gds.journal.messages.TxnAcctEntry) {
        return mergeFrom((io.ewok.gds.journal.messages.TxnAcctEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ewok.gds.journal.messages.TxnAcctEntry other) {
      if (other == io.ewok.gds.journal.messages.TxnAcctEntry.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case TXN_BEGIN: {
          mergeTxnBegin(other.getTxnBegin());
          break;
        }
        case TXN_COMMIT: {
          mergeTxnCommit(other.getTxnCommit());
          break;
        }
        case TXN_ABORT: {
          mergeTxnAbort(other.getTxnAbort());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.ewok.gds.journal.messages.TxnAcctEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.ewok.gds.journal.messages.TxnAcctEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.TxnBegin, io.ewok.gds.journal.messages.TxnBegin.Builder, io.ewok.gds.journal.messages.TxnBeginOrBuilder> txnBeginBuilder_;
    /**
     * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
     */
    public io.ewok.gds.journal.messages.TxnBegin getTxnBegin() {
      if (txnBeginBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (io.ewok.gds.journal.messages.TxnBegin) payload_;
        }
        return io.ewok.gds.journal.messages.TxnBegin.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return txnBeginBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.TxnBegin.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
     */
    public Builder setTxnBegin(io.ewok.gds.journal.messages.TxnBegin value) {
      if (txnBeginBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        txnBeginBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
     */
    public Builder setTxnBegin(
        io.ewok.gds.journal.messages.TxnBegin.Builder builderForValue) {
      if (txnBeginBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        txnBeginBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
     */
    public Builder mergeTxnBegin(io.ewok.gds.journal.messages.TxnBegin value) {
      if (txnBeginBuilder_ == null) {
        if (payloadCase_ == 1 &&
            payload_ != io.ewok.gds.journal.messages.TxnBegin.getDefaultInstance()) {
          payload_ = io.ewok.gds.journal.messages.TxnBegin.newBuilder((io.ewok.gds.journal.messages.TxnBegin) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          txnBeginBuilder_.mergeFrom(value);
        }
        txnBeginBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
     */
    public Builder clearTxnBegin() {
      if (txnBeginBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        txnBeginBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
     */
    public io.ewok.gds.journal.messages.TxnBegin.Builder getTxnBeginBuilder() {
      return getTxnBeginFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
     */
    public io.ewok.gds.journal.messages.TxnBeginOrBuilder getTxnBeginOrBuilder() {
      if ((payloadCase_ == 1) && (txnBeginBuilder_ != null)) {
        return txnBeginBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (io.ewok.gds.journal.messages.TxnBegin) payload_;
        }
        return io.ewok.gds.journal.messages.TxnBegin.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.TxnBegin txn_begin = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.TxnBegin, io.ewok.gds.journal.messages.TxnBegin.Builder, io.ewok.gds.journal.messages.TxnBeginOrBuilder> 
        getTxnBeginFieldBuilder() {
      if (txnBeginBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = io.ewok.gds.journal.messages.TxnBegin.getDefaultInstance();
        }
        txnBeginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.TxnBegin, io.ewok.gds.journal.messages.TxnBegin.Builder, io.ewok.gds.journal.messages.TxnBeginOrBuilder>(
                (io.ewok.gds.journal.messages.TxnBegin) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();;
      return txnBeginBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.TxnCommit, io.ewok.gds.journal.messages.TxnCommit.Builder, io.ewok.gds.journal.messages.TxnCommitOrBuilder> txnCommitBuilder_;
    /**
     * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
     */
    public io.ewok.gds.journal.messages.TxnCommit getTxnCommit() {
      if (txnCommitBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (io.ewok.gds.journal.messages.TxnCommit) payload_;
        }
        return io.ewok.gds.journal.messages.TxnCommit.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return txnCommitBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.TxnCommit.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
     */
    public Builder setTxnCommit(io.ewok.gds.journal.messages.TxnCommit value) {
      if (txnCommitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        txnCommitBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
     */
    public Builder setTxnCommit(
        io.ewok.gds.journal.messages.TxnCommit.Builder builderForValue) {
      if (txnCommitBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        txnCommitBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
     */
    public Builder mergeTxnCommit(io.ewok.gds.journal.messages.TxnCommit value) {
      if (txnCommitBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != io.ewok.gds.journal.messages.TxnCommit.getDefaultInstance()) {
          payload_ = io.ewok.gds.journal.messages.TxnCommit.newBuilder((io.ewok.gds.journal.messages.TxnCommit) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          txnCommitBuilder_.mergeFrom(value);
        }
        txnCommitBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
     */
    public Builder clearTxnCommit() {
      if (txnCommitBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        txnCommitBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
     */
    public io.ewok.gds.journal.messages.TxnCommit.Builder getTxnCommitBuilder() {
      return getTxnCommitFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
     */
    public io.ewok.gds.journal.messages.TxnCommitOrBuilder getTxnCommitOrBuilder() {
      if ((payloadCase_ == 2) && (txnCommitBuilder_ != null)) {
        return txnCommitBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (io.ewok.gds.journal.messages.TxnCommit) payload_;
        }
        return io.ewok.gds.journal.messages.TxnCommit.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.TxnCommit txn_commit = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.TxnCommit, io.ewok.gds.journal.messages.TxnCommit.Builder, io.ewok.gds.journal.messages.TxnCommitOrBuilder> 
        getTxnCommitFieldBuilder() {
      if (txnCommitBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = io.ewok.gds.journal.messages.TxnCommit.getDefaultInstance();
        }
        txnCommitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.TxnCommit, io.ewok.gds.journal.messages.TxnCommit.Builder, io.ewok.gds.journal.messages.TxnCommitOrBuilder>(
                (io.ewok.gds.journal.messages.TxnCommit) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();;
      return txnCommitBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.TxnAbort, io.ewok.gds.journal.messages.TxnAbort.Builder, io.ewok.gds.journal.messages.TxnAbortOrBuilder> txnAbortBuilder_;
    /**
     * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
     */
    public io.ewok.gds.journal.messages.TxnAbort getTxnAbort() {
      if (txnAbortBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (io.ewok.gds.journal.messages.TxnAbort) payload_;
        }
        return io.ewok.gds.journal.messages.TxnAbort.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return txnAbortBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.TxnAbort.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
     */
    public Builder setTxnAbort(io.ewok.gds.journal.messages.TxnAbort value) {
      if (txnAbortBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        txnAbortBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
     */
    public Builder setTxnAbort(
        io.ewok.gds.journal.messages.TxnAbort.Builder builderForValue) {
      if (txnAbortBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        txnAbortBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
     */
    public Builder mergeTxnAbort(io.ewok.gds.journal.messages.TxnAbort value) {
      if (txnAbortBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != io.ewok.gds.journal.messages.TxnAbort.getDefaultInstance()) {
          payload_ = io.ewok.gds.journal.messages.TxnAbort.newBuilder((io.ewok.gds.journal.messages.TxnAbort) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          txnAbortBuilder_.mergeFrom(value);
        }
        txnAbortBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
     */
    public Builder clearTxnAbort() {
      if (txnAbortBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        txnAbortBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
     */
    public io.ewok.gds.journal.messages.TxnAbort.Builder getTxnAbortBuilder() {
      return getTxnAbortFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
     */
    public io.ewok.gds.journal.messages.TxnAbortOrBuilder getTxnAbortOrBuilder() {
      if ((payloadCase_ == 3) && (txnAbortBuilder_ != null)) {
        return txnAbortBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (io.ewok.gds.journal.messages.TxnAbort) payload_;
        }
        return io.ewok.gds.journal.messages.TxnAbort.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.TxnAbort txn_abort = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.TxnAbort, io.ewok.gds.journal.messages.TxnAbort.Builder, io.ewok.gds.journal.messages.TxnAbortOrBuilder> 
        getTxnAbortFieldBuilder() {
      if (txnAbortBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = io.ewok.gds.journal.messages.TxnAbort.getDefaultInstance();
        }
        txnAbortBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.TxnAbort, io.ewok.gds.journal.messages.TxnAbort.Builder, io.ewok.gds.journal.messages.TxnAbortOrBuilder>(
                (io.ewok.gds.journal.messages.TxnAbort) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();;
      return txnAbortBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:gds.wal.TxnAcctEntry)
  }

  // @@protoc_insertion_point(class_scope:gds.wal.TxnAcctEntry)
  private static final io.ewok.gds.journal.messages.TxnAcctEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ewok.gds.journal.messages.TxnAcctEntry();
  }

  public static io.ewok.gds.journal.messages.TxnAcctEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TxnAcctEntry>
      PARSER = new com.google.protobuf.AbstractParser<TxnAcctEntry>() {
    public TxnAcctEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxnAcctEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TxnAcctEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TxnAcctEntry> getParserForType() {
    return PARSER;
  }

  public io.ewok.gds.journal.messages.TxnAcctEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

