// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: journal.proto

package io.ewok.gds.journal.messages;

public interface TxnAbortOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gds.wal.TxnAbort)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 txn_id = 1;</code>
   */
  int getTxnId();
}
