// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: journal.proto

package io.ewok.gds.journal.messages;

/**
 * Protobuf type {@code gds.wal.XLogEntry}
 */
public  final class XLogEntry extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gds.wal.XLogEntry)
    XLogEntryOrBuilder {
  // Use XLogEntry.newBuilder() to construct.
  private XLogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private XLogEntry() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private XLogEntry(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.ewok.gds.journal.messages.XLogEntry.Checkpoint.Builder subBuilder = null;
            if (payloadCase_ == 1) {
              subBuilder = ((io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_).toBuilder();
            }
            payload_ =
                input.readMessage(io.ewok.gds.journal.messages.XLogEntry.Checkpoint.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_);
              payload_ = subBuilder.buildPartial();
            }
            payloadCase_ = 1;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.ewok.gds.journal.messages.XLogEntry.class, io.ewok.gds.journal.messages.XLogEntry.Builder.class);
  }

  public interface CheckpointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gds.wal.XLogEntry.Checkpoint)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code gds.wal.XLogEntry.Checkpoint}
   */
  public  static final class Checkpoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gds.wal.XLogEntry.Checkpoint)
      CheckpointOrBuilder {
    // Use Checkpoint.newBuilder() to construct.
    private Checkpoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Checkpoint() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Checkpoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_Checkpoint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_Checkpoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ewok.gds.journal.messages.XLogEntry.Checkpoint.class, io.ewok.gds.journal.messages.XLogEntry.Checkpoint.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.ewok.gds.journal.messages.XLogEntry.Checkpoint)) {
        return super.equals(obj);
      }
      io.ewok.gds.journal.messages.XLogEntry.Checkpoint other = (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.ewok.gds.journal.messages.XLogEntry.Checkpoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gds.wal.XLogEntry.Checkpoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gds.wal.XLogEntry.Checkpoint)
        io.ewok.gds.journal.messages.XLogEntry.CheckpointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_Checkpoint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_Checkpoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.ewok.gds.journal.messages.XLogEntry.Checkpoint.class, io.ewok.gds.journal.messages.XLogEntry.Checkpoint.Builder.class);
      }

      // Construct using io.ewok.gds.journal.messages.XLogEntry.Checkpoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_Checkpoint_descriptor;
      }

      public io.ewok.gds.journal.messages.XLogEntry.Checkpoint getDefaultInstanceForType() {
        return io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance();
      }

      public io.ewok.gds.journal.messages.XLogEntry.Checkpoint build() {
        io.ewok.gds.journal.messages.XLogEntry.Checkpoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.ewok.gds.journal.messages.XLogEntry.Checkpoint buildPartial() {
        io.ewok.gds.journal.messages.XLogEntry.Checkpoint result = new io.ewok.gds.journal.messages.XLogEntry.Checkpoint(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.ewok.gds.journal.messages.XLogEntry.Checkpoint) {
          return mergeFrom((io.ewok.gds.journal.messages.XLogEntry.Checkpoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.ewok.gds.journal.messages.XLogEntry.Checkpoint other) {
        if (other == io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.ewok.gds.journal.messages.XLogEntry.Checkpoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gds.wal.XLogEntry.Checkpoint)
    }

    // @@protoc_insertion_point(class_scope:gds.wal.XLogEntry.Checkpoint)
    private static final io.ewok.gds.journal.messages.XLogEntry.Checkpoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.ewok.gds.journal.messages.XLogEntry.Checkpoint();
    }

    public static io.ewok.gds.journal.messages.XLogEntry.Checkpoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Checkpoint>
        PARSER = new com.google.protobuf.AbstractParser<Checkpoint>() {
      public Checkpoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Checkpoint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Checkpoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Checkpoint> getParserForType() {
      return PARSER;
    }

    public io.ewok.gds.journal.messages.XLogEntry.Checkpoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int payloadCase_ = 0;
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite {
    CHECKPOINT(1),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1: return CHECKPOINT;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int CHECKPOINT_FIELD_NUMBER = 1;
  /**
   * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
   */
  public io.ewok.gds.journal.messages.XLogEntry.Checkpoint getCheckpoint() {
    if (payloadCase_ == 1) {
       return (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_;
    }
    return io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance();
  }
  /**
   * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
   */
  public io.ewok.gds.journal.messages.XLogEntry.CheckpointOrBuilder getCheckpointOrBuilder() {
    if (payloadCase_ == 1) {
       return (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_;
    }
    return io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.ewok.gds.journal.messages.XLogEntry)) {
      return super.equals(obj);
    }
    io.ewok.gds.journal.messages.XLogEntry other = (io.ewok.gds.journal.messages.XLogEntry) obj;

    boolean result = true;
    result = result && getPayloadCase().equals(
        other.getPayloadCase());
    if (!result) return false;
    switch (payloadCase_) {
      case 1:
        result = result && getCheckpoint()
            .equals(other.getCheckpoint());
        break;
      case 0:
      default:
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + CHECKPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getCheckpoint().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.ewok.gds.journal.messages.XLogEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.ewok.gds.journal.messages.XLogEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gds.wal.XLogEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gds.wal.XLogEntry)
      io.ewok.gds.journal.messages.XLogEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.ewok.gds.journal.messages.XLogEntry.class, io.ewok.gds.journal.messages.XLogEntry.Builder.class);
    }

    // Construct using io.ewok.gds.journal.messages.XLogEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.ewok.gds.journal.messages.JournalProto.internal_static_gds_wal_XLogEntry_descriptor;
    }

    public io.ewok.gds.journal.messages.XLogEntry getDefaultInstanceForType() {
      return io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance();
    }

    public io.ewok.gds.journal.messages.XLogEntry build() {
      io.ewok.gds.journal.messages.XLogEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.ewok.gds.journal.messages.XLogEntry buildPartial() {
      io.ewok.gds.journal.messages.XLogEntry result = new io.ewok.gds.journal.messages.XLogEntry(this);
      if (payloadCase_ == 1) {
        if (checkpointBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = checkpointBuilder_.build();
        }
      }
      result.payloadCase_ = payloadCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.ewok.gds.journal.messages.XLogEntry) {
        return mergeFrom((io.ewok.gds.journal.messages.XLogEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.ewok.gds.journal.messages.XLogEntry other) {
      if (other == io.ewok.gds.journal.messages.XLogEntry.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case CHECKPOINT: {
          mergeCheckpoint(other.getCheckpoint());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.ewok.gds.journal.messages.XLogEntry parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.ewok.gds.journal.messages.XLogEntry) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.XLogEntry.Checkpoint, io.ewok.gds.journal.messages.XLogEntry.Checkpoint.Builder, io.ewok.gds.journal.messages.XLogEntry.CheckpointOrBuilder> checkpointBuilder_;
    /**
     * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
     */
    public io.ewok.gds.journal.messages.XLogEntry.Checkpoint getCheckpoint() {
      if (checkpointBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_;
        }
        return io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return checkpointBuilder_.getMessage();
        }
        return io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
     */
    public Builder setCheckpoint(io.ewok.gds.journal.messages.XLogEntry.Checkpoint value) {
      if (checkpointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        checkpointBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
     */
    public Builder setCheckpoint(
        io.ewok.gds.journal.messages.XLogEntry.Checkpoint.Builder builderForValue) {
      if (checkpointBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        checkpointBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
     */
    public Builder mergeCheckpoint(io.ewok.gds.journal.messages.XLogEntry.Checkpoint value) {
      if (checkpointBuilder_ == null) {
        if (payloadCase_ == 1 &&
            payload_ != io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance()) {
          payload_ = io.ewok.gds.journal.messages.XLogEntry.Checkpoint.newBuilder((io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          checkpointBuilder_.mergeFrom(value);
        }
        checkpointBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
     */
    public Builder clearCheckpoint() {
      if (checkpointBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        checkpointBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
     */
    public io.ewok.gds.journal.messages.XLogEntry.Checkpoint.Builder getCheckpointBuilder() {
      return getCheckpointFieldBuilder().getBuilder();
    }
    /**
     * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
     */
    public io.ewok.gds.journal.messages.XLogEntry.CheckpointOrBuilder getCheckpointOrBuilder() {
      if ((payloadCase_ == 1) && (checkpointBuilder_ != null)) {
        return checkpointBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_;
        }
        return io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance();
      }
    }
    /**
     * <code>.gds.wal.XLogEntry.Checkpoint checkpoint = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.ewok.gds.journal.messages.XLogEntry.Checkpoint, io.ewok.gds.journal.messages.XLogEntry.Checkpoint.Builder, io.ewok.gds.journal.messages.XLogEntry.CheckpointOrBuilder> 
        getCheckpointFieldBuilder() {
      if (checkpointBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = io.ewok.gds.journal.messages.XLogEntry.Checkpoint.getDefaultInstance();
        }
        checkpointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.ewok.gds.journal.messages.XLogEntry.Checkpoint, io.ewok.gds.journal.messages.XLogEntry.Checkpoint.Builder, io.ewok.gds.journal.messages.XLogEntry.CheckpointOrBuilder>(
                (io.ewok.gds.journal.messages.XLogEntry.Checkpoint) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();;
      return checkpointBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:gds.wal.XLogEntry)
  }

  // @@protoc_insertion_point(class_scope:gds.wal.XLogEntry)
  private static final io.ewok.gds.journal.messages.XLogEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.ewok.gds.journal.messages.XLogEntry();
  }

  public static io.ewok.gds.journal.messages.XLogEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<XLogEntry>
      PARSER = new com.google.protobuf.AbstractParser<XLogEntry>() {
    public XLogEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new XLogEntry(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<XLogEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<XLogEntry> getParserForType() {
    return PARSER;
  }

  public io.ewok.gds.journal.messages.XLogEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

